# Generated by Django 5.0.14 on 2026-04-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=100, unique=True)),
                ('name_ru', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name_uz',),
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=150, unique=True)),
                ('name_ru', models.CharField(blank=True, default='', max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('what_we_do_uz', models.JSONField(blank=True, default=list)),
                ('what_we_do_ru', models.JSONField(blank=True, default=list)),
                ('what_we_do_en', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('name_uz',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('tasks_uz', models.JSONField(blank=True, default=list)),
                ('tasks_ru', models.JSONField(blank=True, default=list)),
                ('tasks_en', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('website_url', models.URLField(blank=True)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.category')),
                ('service_types', models.ManyToManyField(related_name='projects', to='core.servicetype')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(blank=True, default='', max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('comment_uz', models.TextField()),
                ('comment_ru', models.TextField(blank=True, default='')),
                ('comment_en', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.portfolioproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
